version: '3'
services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    environment:
      # - SOME_ENV_VARIABLE=some_value
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    environment:
      # - ANOTHER_ENV_VARIABLE=another_value
