version: '3'
services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    volumes:
      - ./app/backend:/app
    ports:
      - 8000:8000
    environment:
      - SOME_ENV_VARIABLE=some_value
      # - SOME_ENV_VARIABLE=some_value
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    volumes:
      - ./app/frontend:/app
    ports:
      - 5000:5000
    environment:
      - ANOTHER_ENV_VARIABLE=another_value
      # - ANOTHER_ENV_VARIABLE=another_value
